Accessing 2D Array

In [1]:
import numpy as np
ls=[[1,2,3] ,
    [4,5,6],
    [7,8,9]]
ls
type(ls)

list

In [2]:
arr2=np.array(ls)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Accessing dimension of the array

In [3]:
arr2.ndim

2

Accessing shape of the array

In [21]:
arr2.shape

(3, 3)

Accessing the index of the array

In [22]:
arr2[0]

array([1, 2, 3])

Multiple row fetching

In [23]:
arr2[0:2]


array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
arr2[-1]

array([7, 8, 9])

In [28]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
arr2[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [85]:
arr2[0:3,1]

array([2, 5, 8])

In [62]:
arr2[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [82]:
arr2[-2:]

array([[4, 5, 6],
       [7, 8, 9]])

In [86]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
arr2[0:,2]

array([3, 6, 9])

Functions of numpy

In [93]:

np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [94]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [96]:
np.linspace(1,50,10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

3 Dimensional array

In [114]:
ls=[[[1, 2, 3], [4, 5, 6], 
     [7, 8, 9]],[[1, 2, 3],
     [4, 5, 6], [7, 8, 9]],
     [[1, 2, 3], [4, 5, 6],
       [7, 8, 9]],[[1, 2, 3],
         [4, 5, 6], [7, 8, 9]]]
ls

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]

In [116]:
arr3=np.array(ls)
arr3


array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [117]:
arr3.shape
# 4 2d array

(4, 3, 3)

In [121]:
arr3.ndim

3

In [122]:
arr3[1]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [133]:
# arr3[0:,0]
arr3[0:4,0,:]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [144]:
arr3[-3:,-3,:]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [147]:
arr3[2,1:,1:]

array([[5, 6],
       [8, 9]])

In [157]:
arr3[0:,1:,1:]

array([[[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]]])

In [164]:
arr3[-4:,-2:,-2:]

array([[[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]]])

In [168]:
arr3[0:,2:,0:]

array([[[7, 8, 9]],

       [[7, 8, 9]],

       [[7, 8, 9]],

       [[7, 8, 9]]])

In [180]:
a=arr3.ravel()
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [183]:
arr3.shape

(4, 3, 3)


argmin: This function returns the index of the smallest element in a 1D array.
argmax: This function returns the index of the largest element in a 1D array.
argsort: This function returns the indices of the sorted elements along an axis of an array. It does not return the sorted array itself.

In [4]:
# argmin to find the index of the smallest element in a 1D array
import numpy as np
arr=np.array([23,45,69,90])
arr
np.argmin(arr)

np.int64(0)

In [5]:
import numpy as np
arr=np.array([45,200,340,56])
arr
np.argmax(arr)

np.int64(2)

In [7]:
# The argsort function in NumPy returns the indices of the sorted elements along an axis of an array. It does not return the sorted array itself.
import numpy as np
arr=np.array([134,21,3,50,700])
arr
np.sort(arr)

array([  3,  21,  50, 134, 700])

In [9]:
import numpy as np

arr = np.array([134, 21, 3, 50, 700])
sorted_indices = np.argsort(arr)

# Reverse the sorted indices
reverse_indices = sorted_indices[::-1]

# Use the reverse indices to get the elements in reverse order
reverse_arr = arr[reverse_indices]

print(reverse_arr)
print(sorted_indices )

[700 134  50  21   3]
[2 1 3 0 4]


In [10]:
import numpy as np

arr = np.array([[5, 2, 9], [1, 7, 3]])
sorted_indices = np.argsort(arr, axis=1)

print(sorted_indices)
# Output:
# [[1 0 2]
#  [0 2 1]]

[[1 0 2]
 [0 2 1]]
